### ISSUE TITLE
http://tsv-utils-dlang.dpldocs.info/tsv-utils-dlang.html

### ISSUE THREAD

**Issue by jondegenhardt** [adamdruppe/dpldocs#2]
(Complete aside: Very cool stuff!)

My repo creates command line tools, not the focus of what you are doing, which is library docs. I was surprised frankly that it worked at for these. So, really, a non-priority for you. But, thought I'd start a thread anyway.

Currently running [http://tsv-utils-dlang.dpldocs.info/tsv-utils-dlang.html](http://tsv-utils-dlang.dpldocs.info/tsv-utils-dlang.html) responds with:

> 404. Try [keep_header.html](http://tsv-utils-dlang.dpldocs.info/keep_header.html) as a starting point

which is not so interesting and doesn't lead anywhere. In my repo each command line tool is a separate subdirectory, `keep-header` is one of the subdirectories. A number of the other directories generate much more interesting/useful docs, eg. [tsv-select](http://tsv-utils-dlang.dpldocs.info/tsv_select.html). More of it is documented in the fashion intended for publishing. Now that there is publishing form I have more reason to go through and document stuff.

Two questions at this point:
- Is there a way I could create a better entry point at the top-level of the repo that would point to the different tools?
- The `common` directory would be interesting to generate docs for, as it contains shared library functions. Some are general enough that other developers might find them interesting. However, the [http://tsv-utils-dlang.dpldocs.info/common.html](http://tsv-utils-dlang.dpldocs.info/common.html) link doesn't work. Should it? Is there a different link?

**Comment by adamdruppe** [comment]
On Fri, Mar 02, 2018 at 08:04:26PM +0000, Jon Degenhardt wrote:
> > 404. Try [keep_header.html](http://tsv-utils-dlang.dpldocs.info/keep_header.html) as a starting point
> 
> which is not so interesting and doesn't lead anywhere.

Right, if it can't find a module matching the package name, it just grabs a random file and says "try this". If you had a module `tsv_utils_dlang` it would use that as home... but I think we can do a bit better if there's a config.

I am considering a bit of expansion to allow html or markdown files so that might be an option too (once I implement it)

> - The `common` directory would be interesting to generate docs for, as it contains shared library functions. Some are general enough that other developers might find them interesting. However, the [http://tsv-utils-dlang.dpldocs.info/common.html](http://tsv-utils-dlang.dpldocs.info/common.html) link doesn't work. Should it? Is there a different link?

So it never cares about your source directories, it only looks at the module name in the D file.

Like this file here:

https://github.com/eBay/tsv-utils-dlang/blob/master/common/src/tsvutil.d#L30

has what looks like a doc comment... but it isn't attached to a `module` definiton, so my generator skips it (I believe ddoc would attach it to the EnablePartialLines thing below, which still isn't quite right but since it does single page for module, it might look ok anyway)

But if you add in `module tsvutil;` right below that comment it should be able to generate for that file.


Just as a general style note though: single-name modules are bad practice since they can so easily conflict with modules from other packages. I'd probably call it `tsv_utils_dlang.tsvutil`... and then change all the times it is imported to match... but I get that's a hassle  so the single word name should work too.

or you could go whole java and call it `com.jondegenhardt.` lol.


I gotta run but I'll have some time to work on this soon so maybe I can implement something for you later today.

**Comment by adamdruppe** [comment]
Check this out:

http://tsv-utils-dlang.dpldocs.info/index.html


New index generation will list all the top-level modules/packages now.

Still not 100% happy with it but it gives a nice listing for your thing at least.

**Comment by jondegenhardt** [comment]
Cool. I know my stuff isn't set up for this documentation, mostly I didn't have much reason to generate documentation from it. It's really such an unexpected thing that I'd be able to produce docs for it. 

As to the module names - yes, I know they are not done correctly. All this came about when I was first learning D, and I just haven't gotten around to fixing those bits yet.

**Comment by jondegenhardt** [comment]
Looking through more of the generate docs - This is fantastic. The actual docs are quite incomplete, but that's strictly because I haven't documented consistently. It should be easy enough to remedy that. Nice work!

**Comment by jondegenhardt** [comment]
Hi @adamdruppe - I finally changed my module structure so the `common` files are found correctly. Also more documentation so that your generator will find it. When I run your generator locally it looks pretty good. I like also that the version on your dpldocs server gets linked from code.dlang.org. 

I'm wondering - is there a way I can trigger a rebuild of the dpldocs documentation, now that it's looking good? I haven't tagged the latest changes (only in master), but it doesn't appear a tagging the release triggers an update. (Also, I changed the repo named since the start of the thread, it's now https://github.com/eBay/tsv-utils.)

**Comment by adamdruppe** [comment]
I haven't documented this yet since I might change the protocol, but right now if you do

```
curl -d clear http://WHATEVER-PROJECT.dpldocs.info/master/reset-cache
```

You can have it delete its cache for the master branch and get it rebuilt on next visit to the site.


But if you tag a release, you can also build the docs for that specific release by going to like

http://tsv-utils.dpldocs.info/v1.2.3/

the specific version tag will be fetched and built.

**Comment by jondegenhardt** [comment]
Thanks! Works like a charm. Again, this is very nice stuff.
